; =======================+-------------+
; Start of contents from |BUILD_FLAGS.h|
; =======================+-------------+

; BUILD FLAGS ================================================
; Change how the game compiles with this one simple trick!
; assembly programmers HATE this!
; ============================================================



; ADDITIONAL FEATURES ========================================
; Some extra things
;
; Kando's Fun Stuff
; uncomment to enable kandowontu's added features that aren't
; in vanilla geometry dash.
_FLAG_KANDO_FUN_STUFF = 1
; ============================================================



; DEBUGGING FEATURES =========================================
; Useful stuff for making a ROM hack or mod.
;
; Enable Test Levels
; uncomment to enable every level id. will break after TEST4.
; #define FLAG_ENABLE_TEST_LEVELS
;
; Print Metatiles When Compiling
; set to 1 to display metatile data when compiling via the
; command line.
_PRINT_METATILES = 0
;
; Enable Debug Mode
; Activated by pressing SELECT during gameplay
; Recommended to be disabled for release builds
_DEBUG_MODE_ENABLED = 1
;
; Enable kandokidshackX Variables
; Activated in convoluted methods
_KANDOKIDSHACKX_ENABLED = 1
; ============================================================



; VERSION NUMBER STUFF =======================================
; These change how the version number is displayed.
;
; Enable Version Number
; uncomment to enable the version number on the credits screen
; you can ignore everything below this if disabled.
_FLAG_ENABLE_VER_NUM = 1
;
; Beta Build
; uncomment if compiling a demo or beta build.
_FLAG_BETA_BUILD = 1
;
; Major Version Number 
; set if releasing a demo/beta.
_FLAG_MAJ_VER = '1'
;
; Minor Version Number
; increment by 1 for officially released patches.
_FLAG_MIN_VER = '2'
;
; Patch Version Number
; increment by 1 for patches
_FLAG_PATCH_VER = '8'
; ============================================================



; OPTIMIZATION SETTINGS ======================================
; Speed up parts of the game with these flag(s).
;
; Use Illegal Opcodes
; set this to 1 to *slightly* speed up some code in nesdash.s.
; real Famicoms/NESs should have no problems executing code
; with such opcodes, but clone CPUs in Famiclones such as
; Dendy as well as some emulators do not execute those
; reliably, therefore we advise to have it turned off for
; maximum hardware compatibility.
_USE_ILLEGAL_OPCODES = 0
; ============================================================



; ADVANCED SETTINGS ==========================================
; !! ONLY CHANGE IF YOU KNOW WHAT YOU'RE DOING !!
;
; Save File Version
; increase by 1 if SRAM values are added, changed or deleted.
_FLAG_SAVE_VER = $24
; ============================================================
; =======================+---------------------------------------+
; Start of contents from |LEVELS/include/lvlset_A/level_defines.h|
; =======================+---------------------------------------+


; Generated by export_levels.py

_LEVELSET = 'A'

_OFFICIAL_LEVEL_COUNT = 25
_COMMUNITY_LEVEL_COUNT = 19

_level_stereomadness = 0
_level_backontrack = 1
_level_polargeist = 2
_level_dryout = 3
_level_baseafterbase = 4
_level_cantletgo = 5
_level_jumper = 6
_level_timemachine = 7
_level_cycles = 8
_level_xstep = 9
_level_clutterfunk = 10
_level_theoryofeverything = 11
_level_electromanadventures = 12
_level_clubstep = 13
_level_electrodynamix = 14
_level_hexagonforce = 15
_level_blastprocessing = 16
_level_toe2 = 17
_level_geometricaldominator = 18
_level_deadlocked = 19
_level_fingerdash = 20
_level_dash = 21
_level_thetower = 22
_level_thesewers = 23
_level_thechallenge = 24
_level_retray = 25
_level_leveleasy = 26
_level_dorabaebasic4 = 27
_level_dorabaebasic6 = 28
_level_dreamer = 29
_level_groundtospace = 30
_level_subzero = 31
_level_kappaclysm = 32
_level_sunshine = 33
_level_revolution = 34
_level_funnygameholiday = 35
_level_lostinthewoods = 36
_level_bloodbathbutno = 37
_level_rainbowtylenol = 38
_level_greif = 39
_level_extraordinaryexcitement = 40
_level_thelightningroad = 41
_level_nightmare = 42
_level_firetemple = 43

; =======================+-----------------------------+
; Start of contents from |SAUCE/defines/space_defines.h|
; =======================+-----------------------------+

.ifdef _FLAG_ENABLE_TEST_LEVELS
	_LEVEL_COUNT = 256
.else
	_LEVEL_COUNT = (_OFFICIAL_LEVEL_COUNT)
.endif

.ifdef _FLAG_ENABLE_TEST_LEVELS
	_LEVEL_COUNT2 = 256
.else
	_LEVEL_COUNT2 = (_OFFICIAL_LEVEL_COUNT+_COMMUNITY_LEVEL_COUNT)
.endif

_TOTAL_LEVEL_COUNT = (_OFFICIAL_LEVEL_COUNT+_COMMUNITY_LEVEL_COUNT)

.if ___HUGE_ROM
_MAX_ICONS = 25 ;total icons
.else
_MAX_ICONS = 26 ;total icons
.endif
_MAX_FIREBALLS = 20
_MAX_PRACTICE_POINTS = 8
_max_loaded_sprites = 16
_MAX_LEVEL_COMPLETE = $80 ;129 levels max (increase if we get more)

_NINJABANK = 92
_FOOTBALLBANK = 94
_MOUSEBANK = 96
_LETTERBANK = 111
_MENUBANK = 98
_MENUICONBANK = 102
_LEVELCOMPLETEBANK = 106
_PRACTICECOMPLETEBANK = 110

_SPIKESA = 0
_SPIKESB = 2
_SPIKESC = 4
_BLOCKSA = 6
_BLOCKSB = 8
_BLOCKSC = 10
_BLOCKSD = 12
_SAWBLADESA = 14
_SLOPESA = 16

_DECO1 = 28
_DECOCLOUD = 32
_EXTRASPRITES1 = 36

_FAMISTUDIO_STATE_SIZE = 172
_FAMISTUDIO_OUTPUT_BUF_SIZE = 11

.if !___THE_ALBUM
.define _MOVEMENT_BANK "XCD_BANK_01"
.define _BACKGROUND_RENDER_BANK "XCD_BANK_02"
.define _DIALOG_BOX_BANK "XCD_BANK_02"
.define _SCROLL_BANK "XCD_BANK_04"
.define _SPRITE_RENDER_BANK "XCD_BANK_04"
.define _PLAYER_RENDER_BANK "XCD_BANK_05"
.define _RESETLEVEL_BANK "XCD_BANK_06"
.endif
.define _GROUND_BANK "XCD_BANK_06"
.if !___HUGE_ROM
.define _LVLDONE_BANK "XCD_BANK_06"
.else
.define _LVLDONE_BANK "XCD_BANK_08"
.endif
; =======================+-------------------------------+
; Start of contents from |SAUCE/defines/physics_defines.h|
; =======================+-------------------------------+

_ORB_HEIGHT_YELLOW_UPSIDE2 = (-$580) ; unused


_GRAVITY_DOWN = $00
_GRAVITY_UP = $FF
; MACRO: _invert_gravity(var) = (var ^= 0xFF)
